export const state = {
    scene: null,
    camera: null,
    renderer: null,
    yaw: 0,
    pitch: 0,
    isLocked: false,
    isModalOpen: false,
    moveForward: false,
    moveBackward: false,
    moveLeft: false,
    moveRight: false,
    velocity: new THREE.Vector3(),
    direction: new THREE.Vector3(),
    clock: new THREE.Clock(),
    keysPressed: {},
    collisionBounds: { x: 10, z: 10 },
    playerHeight: 1.6,
    raycaster: null,
    screenMeshes: [],
    targetableTerminal: null,
    TERMINAL_DATA: null,
    lookSensitivity: 0.0022,
    moveSpeed: 45.0,
    friction: 10.0,
    blocker: null,
    instructions: null,
    playButton: null,
    posDisplay: null,
    scoreDisplay: null,
    interactionPrompt: null,
    detailModal: null,
    closeModal: null,
    modalTitle: null,
    modalBody: null,
    screenStates: {},
    laserBeams: [],
    particleSystems: [],
    hits: 0,
    misses: 0
};
