export const state = {
    scene: null,
    camera: null,
    renderer: null,
    yaw: 0,
    pitch: 0,
    isLocked: false,
    isZoomed: false,
    moveForward: false,
    moveBackward: false,
    moveLeft: false,
    moveRight: false,
    touchMoveForward: false,
    touchMoveBackward: false,
    touchMoveLeft: false,
    touchMoveRight: false,
    velocity: new THREE.Vector3(),
    direction: new THREE.Vector3(),
    clock: new THREE.Clock(),
    keysPressed: {},
    collisionBounds: { x: 10, z: 10 },
    playerHeight: 1.6,
    raycaster: null,
    screenMeshes: [],
    targetableTerminal: null,
    TERMINAL_DATA: null,
    lookSensitivity: 0.0022,
    moveSpeed: 45.0,
    friction: 10.0,
    blocker: null,
    instructions: null,
    playButton: null,
    posDisplay: null,
    scoreDisplay: null,
    interactionPrompt: null,
    screenStates: {},
    laserBeams: [],
    particleSystems: [],
    hits: 0,
    misses: 0,
    weaponBobContainer: null,
    swayX: 0,
    swayY: 0,
    targetSwayX: 0,
    targetSwayY: 0,
    profilePicImage: null,
    championAwardImage: null,
    blocknotePostImage: null
};
